### ISSUE TITLE
Outlier point in NN Correlation

### ISSUE THREAD

**Issue by vduret** [rmjarvis/TreeCorr#162] opened 2023-10-04 11:33 UTC
Hello,

When I measure the angular two-point correlation function, I sometimes have an outlier point with a much lower amplitude and when it happens, it is systematically in the first angular bin. See the figure :
![angular_2pcf_sdss](https://github.com/rmjarvis/TreeCorr/assets/88327600/d1f9ed99-8fd0-4fef-90ed-586f4abcc907)

The binning here is linear between 3.5° and 6.5° for the first two redshift bins, 2.5° to 5.5° for the last one, with 20 bins each time. The outlier is observed for all jackknife samples.
What could cause this behaviour ? 

Thank you,

Vincent

**Comment by rmjarvis** [comment] 2023-10-04 14:26
My best guess without more information is masking.  If your random catalog doesn't fully capture the masking (either explicit or implicit from selection due to detection issues around foregrounds), then the inferred correlation at small scales will be too small.  If extreme enough, it could go negative.

**Comment by vduret** [comment] 2023-10-16 14:55
I am working on a mock galaxy catalogue so for the randoms, the mask used is only the angular selection.
I have checked that this behaviour can happen using the same data, same randoms and even with the same jackknife patches, only changing the binning of the measurement (min_sep, max_sep and nbins). I am using bin_slop = 1 since I had a negligible effect on the result when using smaller values.
I can't share the plot since the data is not public but here is a representation of the comparison of the two successive measurements : 
![2pcf_outlier_1](https://github.com/rmjarvis/TreeCorr/assets/88327600/3b72035d-090a-4a22-a793-5ec39c179244)

I have also another comparison, this time with different randoms but showing a very good agreement on the autocorrelations of 13 redshift bins, except for these outliers :
![2pcf_outlier_2](https://github.com/rmjarvis/TreeCorr/assets/88327600/f72464d6-b5e5-49e9-b830-a24a2466dc66)

I also had the case where the outliers where only in the 2nd and 3rd redshift bins, still in the first angular bin.

**Comment by rmjarvis** [comment] 2023-10-16 21:58
Looking at the derived w(theta) probably isn't the most instructive here.  I'd look at the individual DD, DR and RR values to see which one is driving the behavior.  If you can generate a small piece of code that reproduces this, not based on proprietary data, I can take a look.

**Comment by akritiasto** [comment] 2024-10-16 14:17
@rmjarvis I am facing a similar issue of outliers. Here I am attaching the DD,DR,RR and 2pcf. Could you please help me resolve this issue
![nn](https://github.com/user-attachments/as
![wtheta](https://github.com/user-attachments/assets/a7371bb2-8df1-47e6-9c4b-88ff4fabb736)

![rr](https://github.com/user-attachments/assets/8582b076-8863-4a17-9c40-f78e6bae2e8a)
sets/fb2e57f9-f307-4362-a3f2-943962734d84)
![dr](https://github.com/user-attachments/assets/c3dbc1ab-c4ee-47af-b8dd-16f83ddbc766)

**Comment by akritiasto** [comment] 2024-10-16 18:14
@rmjarvis Thanks for the quick reply. I have not put any mask on randoms. Here is the image of my data and randoms.
[data_randoms_full100.pdf](https://github.com/user-attachments/files/17400953/data_randoms_full100.pdf)

**Comment by rmjarvis** [comment] 2024-10-16 18:42
Another workaround seems to be to lower bin_slop a lot.  I get relatively sensible results with bin_slop=1.e-5, and it doesn't take much longer than the default (which gives the wonky results).  Going even lower to 1.e-6 looks even more accurate, but takes much longer.  That shouldn't be required of course, but it's probably a clue for me to find the bug, and it might let you achieve reasonable results without much change to your code.

**Comment by akritiasto** [comment] 2024-10-16 19:50
@rmjarvis Thank you! Changing the bin_slop to 1e-6 is giving me reasonable results now!

**Comment by rmjarvis** [comment] 2024-10-17 18:03
I found the bug.  cf. https://github.com/rmjarvis/TreeCorr/pull/176
I'll release version 5.0.1 with this fix shortly.

**Comment by rmjarvis** [comment] 2024-10-17 18:07
With this version, the default bin_slop should be fairly accurate.  As good as what you get now with bin_slop=1.e-6, but much faster.

**Comment by rmjarvis** [comment] 2024-10-18 05:36
v5.0.2 is released with this bug fixed.  Thanks for the bug report!  

@vduret I suspect this will fix the behavior you were seeing as well. But please reopen if this hasn't fixed your problem.

**Closed by rmjarvis** 2024-10-18 05:36 UTC
Labels: bug
